"""Contains the features' labels. These are used for plotting."""

features_labels = {
    "CC_to_C_rate": "$CC$ to $C$ rate",
    "CD_to_C_rate": "$CD$ to $C$ rate",
    "DC_to_C_rate": "$DC$ to $C$ rate",
    "DD_to_C_rate": "$DD$ to $C$ rate",
    "SSE": "SSE",
    "Makes_use_of_game": "Make use of game",
    "Makes_use_of_length": "Make use of length",
    "Stochastic": "stochastic",
    "Cooperation_rating": r"$C_r$",
    "Cooperation_rating_max": r"$C_{max}$",
    "Cooperation_rating_min": r"$C_{min}$",
    "Cooperation_rating_median": r"$C_{median}$",
    "Cooperation_rating_mean": r"$C_{mean}$",
    "Cooperation_rating_comp_to_max": r"$C_r$ / $C_{max}$ ",
    "Cooperation_rating_comp_to_min": r"$C_{min}$ / $C_r$",
    "Cooperation_rating_comp_to_median": r"$C_r$ / $C_{median}$",
    "Cooperation_rating_comp_to_mean": r"$C_r$ / $C_{mean}$",
    "turns": r"$n$",
    "noise": r"$p_n$",
    "probend": r"$p_e$",
    "Normalized_Rank": r"$r$",
    "Median_score": "Median score",
    "size": r"$N$",
    "memory_usage": "memory usage",
    "repetitions": r"$k$",
}
